### ISSUE TITLE
Spring Boot 2.3.0 / Kubernetes probes / Use liveness and readiness probes from Spring Boot 2.3.0

### ISSUE THREAD

**Issue by gytis** [snowdrop/spring-boot-health-check-booster#55]
https://spring.io/blog/2020/03/25/liveness-and-readiness-probes-with-spring-boot

**Comment by cmoulliard** [comment]
Can you apply the label that we need to display it correctly under the category when the report is populated please ? @aureamunoz

**Comment by jacobdotcosta** [comment]
It isn't showing up in the report because this repo is not being included. I'm working on it.
